<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "chuyenkhoa".
 *
 * @property int $id
 * @property string $title
 * @property string $image
 * @property string $job
 * @property string $content
 * @property int $ord
 * @property int $active
 * @property int $lang_id
 * @property string $noidung
 * @property string $url
 */
class Chuyenkhoa extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'chuyenkhoa';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'ord'], 'required'],
            [['image','noidung','url', 'content'], 'string'],
            [['ord', 'active', 'lang_id'], 'integer'],
            [['title', 'job'], 'string', 'max' => 200],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Tên',
            'image' => 'Hình ảnh',
            'job' => 'Chức vụ',
            'content' => 'Mô tả',
            'ord' => 'Thứ tự',
            'active' => 'Hoạt động',
            'lang_id' => 'Lang ID',
            'noidung' => 'Nội dung',
        ];
    }
    public function afterDelete()
    {
        $path = dirname(dirname(__DIR__)) . '/images/comment/' . $this->image;
        if (is_file($path))
            unlink($path);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
    public static function getComment()
    {
        return self::find()->where(['active'=>1])->orderBy(['ord'=>SORT_ASC])->all();
    }
    public function afterSave($insert, $changedAttributes)
    {
        self::updateAll(['url'=>"/".\func::taoduongdan($this->title)."-ck".$this->id.".html"],['id'=>$this->id]);

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->lang_id=Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function getUrl(){
        return Yii::$app->urlManager->createUrl(['site/chuyenkhoas','id'=>$this->id,'name'=>\func::taoduongdan(substr($this->title,0,50))]);
    }
}
