<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "comment".
 *
 * @property int $id
 * @property string $name
 * @property string $image
 * @property string $job
 * @property string $content
 * @property string $address
 * @property int $ord
 * @property int $active
 * @property int $lang_id
 */
class Comment extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comment';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'image', 'content', 'ord'], 'required'],
            [['image', 'content', 'address'], 'string'],
            [['ord', 'active', 'lang_id'], 'integer'],
            [['name', 'job'], 'string', 'max' => 200],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên',
            'image' => 'Hình ảnh',
            'job' => 'Job',
            'content' => 'Nội dung',
            'address' => 'Địa chỉ',
            'ord' => 'Ord',
            'active' => 'Hoạt động',
            'lang_id' => 'Lang ID',
        ];
    }
    public function afterDelete()
    {
        $path = dirname(dirname(__DIR__)) . '/images/comment/' . $this->image;
        if (is_file($path))
            unlink($path);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
    public static function getComment()
    {
        return self::find()->where(['active'=>1])->orderBy(['ord'=>SORT_ASC])->all();
    }
}
