<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "page".
 *
 * @property int $id
 * @property string $title
 * @property string $url
 * @property string $content
 * @property string $seo_title
 * @property string $seo_desc
 * @property string $seo_keyword
 * @property int $active
 * @property int $check
 * @property string $product
 * @property int $ord
 * @property int $lang_id
 * @property string $brief
 * @property string $image
 */
class Page extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'page';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['url', 'content', 'brief', 'seo_desc', 'product', 'image'], 'string'],
            [['active','check', 'ord', 'lang_id'], 'integer'],
            [['title', 'seo_title', 'seo_keyword'], 'string', 'max' => 200],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Tiêu đề',
            'url' => 'Đường dẫn',
            'content' => 'Mô tả',
            'seo_title' => 'Seo Title',
            'seo_desc' => 'Seo Desc',
            'seo_keyword' => 'Seo Keyword',
            'active' => 'Hoạt động',
            'product' => 'Sản phẩm',
            'ord' => 'Thứ tự',
            'lang_id' => 'Người đăng',
            'brief' => 'Tóm tắt',
            'image' => 'Hình ảnh',
            'check' => 'Hiển thị giao diện trang chủ'
        ];
    }
   public function afterSave($insert, $changedAttributes)
   {
       self::updateAll(['url'=>"/".\func::taoduongdan($this->title)."-b".$this->id.".html"],['id'=>$this->id]);

       parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
   }
   public function beforeSave($insert)
   {
       if($this->isNewRecord){
           $this->lang_id=Yii::$app->user->identity->id;
       }
       return parent::beforeSave($insert); // TODO: Change the autogenerated stub
   }
}
