<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "quytrinh".
 *
 * @property int $id
 * @property string $name
 * @property string $title
 * @property string $decription
 * @property int $active
 * @property int $ord
 * @property string $image
 */
class Quytrinh extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quytrinh';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['decription'], 'string'],
            [['active', 'ord'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['image','title'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'title' => 'Title',
            'decription' => 'Decription',
            'active' => 'Active',
            'ord' => 'Ord',
            'image' => "Hình ảnh"
        ];
    }
    public function afterDelete()
    {
        $path = dirname(dirname(__DIR__)) . '/images/quytrinh/' . $this->image;
        if (is_file($path))
            unlink($path);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
    public static function getQuytrinh()
    {
        return self::find()->where(['active'=>1])->orderBy(['ord'=>SORT_ASC])->all();
    }
}
